### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by AndreaGhiroldi** [vittoriofortino84/COPS#2]
Hi, I'm trying to install the package on R, version 4.2.2 but I can't install since there is a problem with the clustCrit package (it is not available for this version of R). I've also tried with the 4.1.2 version, but I've encountered the same problem. Can you help me?

Thank you

**Comment by trintala** [comment]
Hi, I think you are probably referring to the clusterCrit package that COPS depends on for clustering quality metrics. It seems that this package was recently archived in CRAN due to their policy of removing packages which do not pass the package build checks without warnings in newer versions of R. Likely it still functions correctly and can be installed from the CRAN GitHub archive like this:
`devtools::install_github("cran/clusterCrit")`
I will update the installation instructions and consider alternative implementations for the future.
